name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.15.0
      with:
        swift-version: "5.6.1"
    - name: Build
      run: swift build --disable-sandbox -v
    - name: Run tests
      run: swift test -v